# Generated by Django 2.2.16 on 2020-09-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedpage',
            name='background_image',
            field=models.FileField(upload_to='development/django-content-server/media/Posts'),
        ),
        migrations.AlterField(
            model_name='pagedetailextension',
            name='file',
            field=models.FileField(upload_to='development/django-content-server/media/Posts'),
        ),
        migrations.AlterField(
            model_name='pagedetailextension',
            name='image',
            field=models.ImageField(upload_to='development/django-content-server/media/Posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='development/django-content-server/media/Posts'),
        ),
    ]
