# Generated by Django 2.2.16 on 2020-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200930_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('class_names', models.CharField(max_length=150)),
                ('id_names', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BeautifulGoogleSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=75)),
                ('link', models.URLField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('allowed', models.ForeignKey(on_delete='cascade', to='api.AllowedDomain')),
            ],
        ),
        migrations.CreateModel(
            name='BeautifulGoogleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('subtitle', models.CharField(max_length=75)),
                ('abstract', models.TextField(blank=True)),
                ('image', models.CharField(max_length=75)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('bgs', models.ForeignKey(on_delete='cascade', to='api.BeautifulGoogleSearch')),
            ],
        ),
    ]
