# Generated by Django 2.2.16 on 2020-10-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201018_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gumtreelocation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GumtreeProvince'),
        ),
    ]
