# Generated by Django 2.2.16 on 2020-10-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201018_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautifulgumtreequery',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='api.GumtreeCategory'),
        ),
        migrations.AlterField(
            model_name='beautifulgumtreequery',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GumtreeCategoryLabel'),
        ),
        migrations.AlterField(
            model_name='beautifulgumtreequery',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='api.GumtreeLocation'),
        ),
        migrations.AlterField(
            model_name='beautifulgumtreequery',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GumtreeProvince'),
        ),
    ]
