# Generated by Django 2.2.16 on 2020-10-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alloweddomain_beautifulgoogleresult_beautifulgooglesearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddomain',
            name='domain',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alloweddomain',
            name='term',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
