# Generated by Django 2.2.16 on 2020-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201019_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautifulgumtreequery',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beautifulgumtreequery',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.GumtreeCategory'),
        ),
        migrations.AlterField(
            model_name='beautifulgumtreequery',
            name='location',
            field=models.ManyToManyField(blank=True, to='api.GumtreeLocation'),
        ),
    ]
