# Generated by Django 2.2.16 on 2020-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171110_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='development/django-content-server/media/audo'),
        ),
    ]
